<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1519683003933' stop='1519683003990'>
    <name>API ./GET background.png</name>
    <title>API ./GET background.png</title>
    <test-cases>
        <test-case start='1519683003933' status='failed' stop='1519683003990'>
            <name>check existence background.png</name>
            <title>check existence background.png</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>
                      AssertionError: expected [Error: Not Found] to have status code 200 but got 404
                      + expected - actual
                
                      -404
                      +200
                      </message>
                <stack-trace>      at Context.it (test/auth.js:101:27)
                      at &lt;anonymous>
                      at process._tickCallback (internal/process/next_tick.js:188:7)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>