<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1519683005592' stop='1519683006620'>
    <name>API ./Register of new user check status of request</name>
    <title>API ./Register of new user check status of request</title>
    <test-cases>
        <test-case start='1519683005592' status='passed' stop='1519683005741'>
            <name>register with correct values (await status 200)</name>
            <title>register with correct values (await status 200)</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
        </test-case>
        <test-case start='1519683005741' status='failed' stop='1519683005892'>
            <name>register with incorrect email (await status 400)</name>
            <title>register with incorrect email (await status 400)</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>
                      AssertionError: expected { Object (domain, _events, ...) } to have status code 400 but got 200
                      + expected - actual
                
                      -200
                      +400
                      </message>
                <stack-trace>      at Context.it (test/register.js:129:31)
                      at &lt;anonymous>
                      at process._tickCallback (internal/process/next_tick.js:188:7)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1519683005892' status='failed' stop='1519683006090'>
            <name>register with incorrect login (count of symbols more than 16) (await status 400)</name>
            <title>register with incorrect login (count of symbols more than 16) (await status 400)</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>
                      AssertionError: expected { Object (domain, _events, ...) } to have status code 400 but got 200
                      + expected - actual
                
                      -200
                      +400
                      </message>
                <stack-trace>      at Context.it (test/register.js:148:31)
                      at &lt;anonymous>
                      at process._tickCallback (internal/process/next_tick.js:188:7)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1519683006090' status='failed' stop='1519683006246'>
            <name>register with incorrect password (with spaces) (await status 400)</name>
            <title>register with incorrect password (with spaces) (await status 400)</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>
                      AssertionError: expected { Object (domain, _events, ...) } to have status code 400 but got 200
                      + expected - actual
                
                      -200
                      +400
                      </message>
                <stack-trace>      at Context.it (test/register.js:167:31)
                      at &lt;anonymous>
                      at process._tickCallback (internal/process/next_tick.js:188:7)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1519683006246' status='failed' stop='1519683006458'>
            <name>register with incorrect password_confirm (await status 400)</name>
            <title>register with incorrect password_confirm (await status 400)</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>
                      AssertionError: expected { Object (domain, _events, ...) } to have status code 400 but got 200
                      + expected - actual
                
                      -200
                      +400
                      </message>
                <stack-trace>      at Context.it (test/register.js:186:31)
                      at &lt;anonymous>
                      at process._tickCallback (internal/process/next_tick.js:188:7)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1519683006459' status='failed' stop='1519683006620'>
            <name>register with incorrect sex (await status 400)</name>
            <title>register with incorrect sex (await status 400)</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>
                      AssertionError: expected { Object (domain, _events, ...) } to have status code 400 but got 200
                      + expected - actual
                
                      -200
                      +400
                      </message>
                <stack-trace>      at Context.it (test/register.js:205:31)
                      at &lt;anonymous>
                      at process._tickCallback (internal/process/next_tick.js:188:7)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>